# ------------------------------
# API INGRESS (needs rewrite)
# ------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: weather.local
      http:
        paths:
        - path: /api(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: weather-backend
              port:
                number: 8081
---
# ------------------------------
# FRONTEND INGRESS (NO rewrite)
# ------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-frontend-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: weather.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: weather-frontend
              port:
                number: 80
