- name: Apply MySQL Deployment
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "{{ playbook_dir }}/../../k8s/mysql-deployment.yaml"

- name: Apply MySQL Service
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "{{ playbook_dir }}/../../k8s/mysql-service.yaml"

- name: Apply Backend Deployment
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "{{ playbook_dir }}/../../k8s/backend-deployment.yaml"

- name: Apply Backend Service
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "{{ playbook_dir }}/../../k8s/backend-service.yaml"

- name: Apply Frontend Deployment
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "{{ playbook_dir }}/../../k8s/frontend-deployment.yaml"

- name: Apply Frontend Service
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "{{ playbook_dir }}/../../k8s/frontend-service.yaml"

- name: Apply Ingress Resources
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "{{ playbook_dir }}/../../k8s/ingress.yaml"
